- name: configuring frontend server
  hosts: frontend
  become: yes
  vars:

  tasks: #list of tasks
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: starting and enabiling nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: removing all files in html folder
    ansible.builtin.file:
      path: rm -rf /usr/share/nginx/html/*
      state: absent
  
  - name: downloading and unarchive
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copying expense conf file
    ansible.builtin.copy:
      src: /home/ec2-user/203-expense-ansible/expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restarting nginx
    ansible.builtin.service:
      name: nginx
      state: restarted